apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pv-claim
spec:
  resources:
    requests:
      storage: {{ .Values.database.dbstorage }}
  accessModes:
    - ReadWriteOnce